previews:
  generation: manual

services:
- type: web
  name: dcp-portal
  runtime: node
  region: oregon
  plan: starter
  rootDir: dcp-portal
  buildCommand: npm install --no-audit --no-fund && npm run build
  startCommand: npm start
  envVars:
  - key: NODE_VERSION
    value: "20.11.1"
  - key: CENTRAL_BASE_URL
    sync: false
  - key: CENTRAL_AUTH_SCHEME
    value: Bearer
  - key: CENTRAL_TOKEN
    sync: false
  - key: PORTAL_PUBLIC_BASE_URL
    value: ${RENDER_EXTERNAL_URL}
  - key: IMPORTER_INTERNAL_HOSTPORT
    fromService: { name: dcp-importer, type: pserv, property: hostport }
  - key: CLEANER_INTERNAL_HOSTPORT
    fromService: { name: dcp-cleaner, type: pserv, property: hostport }
  - key: INTEGRATIONS_INTERNAL_HOSTPORT
    fromService: { name: dcp-integrations, type: pserv, property: hostport }
  healthCheckPath: /

- type: pserv
  name: dcp-cleaner
  runtime: python
  region: oregon
  plan: starter
  rootDir: dcp-cleaner
  buildCommand: pip install --upgrade pip setuptools wheel && pip install --prefer-binary -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  envVars:
  - key: PYTHON_VERSION
    value: "3.11.9"

- type: pserv
  name: dcp-importer
  runtime: python
  region: oregon
  plan: starter
  rootDir: dcp-importer
  buildCommand: pip install --upgrade pip setuptools wheel && pip install --prefer-binary -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  envVars:
  - key: PYTHON_VERSION
    value: "3.11.9"

- type: pserv
  name: dcp-integrations
  runtime: python
  region: oregon
  plan: starter
  rootDir: dcp-integrations
  buildCommand: pip install --upgrade pip setuptools wheel && pip install --prefer-binary -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  envVars:
  - key: PYTHON_VERSION
    value: "3.11.9"
